export const CREATE_EARNING_REQUEST = 'CREATE_EARNING_REQUEST';
export const CREATE_EARNING_SUCCESS = 'CREATE_EARNING_SUCCESS';
export const CREATE_EARNING_FAILURE = 'CREATE_EARNING_FAILURE';

export const ALL_EARNING_REQUEST = "ALL_EARNING_REQUEST";
export const ALL_EARNING_SUCCESS = "ALL_EARNING_SUCCESS";
export const ALL_EARNING_FAIL = "ALL_EARNING_FAIL";
 
export const USER_EARNINGS_REQUEST = "USER_EARNING_REQUEST";
export const USER_EARNINGS_SUCCESS = "USER_EARNING_REQUEST"; 
export const USER_EARNINGS_FAIL = "USER_EARNING_REQUEST";

export const CLEAR_ERRORS = "CLEAR ERRORS";  